### ISSUE TITLE
Coordinate System Axis: `rangeMeaning` is not getting extracted, `maxValue` and `minValue` may or may not be

### ISSUE THREAD

**Issue by strogonoff** [isogr/register-system-transition#14]
- rangeMeaning can be “exact” or “wraparound”, if maxValue and minValue are present
- maxValue and minValue can be missing (null), but need to check they are migrated if they exist
- extract maxValue and minValue as strings

**Comment by stefanomunarini** [comment]
None of the entries in https://geodetic.isotc211.org/register/geodetic/CoordinateSystemAxis shows data for rangeMeaning, maxValue and minValue. The database dump also does not have any data for those fields (see attached image).
<img width="855" alt="Screenshot 2024-01-10 at 11 41 12" src="https://github.com/isogr/data-extraction-tools/assets/4653319/8e0c7b2f-efc5-4f21-86ef-396b8db1bd4e">

**Comment by stefanomunarini** [comment]
I have included `rangeMeaning` as a required property (https://github.com/isogr/register-system-transition/pull/24/files and https://github.com/isogr/registry/pull/21/files)

As for now, all of the coordinate-sys-axis entries do not contain a minValue, maxValue or rangeMeaning (as for https://github.com/isogr/register-system-transition/issues/14#issuecomment-1884773426), thus all those fields values are None.

**Comment by strogonoff** [comment]
For transition period, we’ll focus on issues assigned to milestones…

**Comment by ribose-jeffreylau** [comment]
@stefanomunarini Apologies, yes I did close it by mistake :p

Thanks for spotting it... otherwise it would have gone unnoticed!

**Comment by stefanomunarini** [comment]
Merged relevant PR. Closing this
