### ISSUE TITLE
Files encoded as ASCII with Unicode entities

### ISSUE THREAD

**Issue by strogonoff** [isogr/register-system-transition#15]
In [this file](https://github.com/isogr/registry/tree/master/gr-registry/unit-of-measurement/d978906c-4d5c-42fe-8133-e36c6fa4002e.yaml), there’s this line:

```
  - "\xB5m/m/a"
```

Since files are encoded in UTF-8, it can be written normally:

```
  - "µm/m/a"
```

Not sure yet whether it may cause bugs in future. The string is displayed correctly on the front-end for now, I suppose JS YAML deserializer handles these entities.

**Comment by stefanomunarini** [comment]
I run the script allowing for unicode characters and tested the dataset using Paneron, and everything is working correctly. Pushed the data to the [gr-registry](https://github.com/isogr/registry/commit/dd8a76cfa80083bc12bc64a6bad2c048020aaf65)  and updated the [dump script](https://github.com/isogr/register-system-transition/commit/d9705915fcaaa1e4b0ef6f43ccc657d8f86851b2).
