### ISSUE TITLE
Make a full snapshot of the current system available as a static site

### ISSUE THREAD

**Issue by strogonoff** [isogr/register-system-transition#18]
- [x] We’d want to have both the snapshot itself and the script that creates/updates it in this repository. The snapshot have to be updated at least once at the end of January.
- [ ] We want to have the snapshot up & running under `geodetic-static.isotc211.org` until it replaces the current Java instance.

**Comment by ribose-jeffreylau** [comment]
Right now, the snapshot is being served at https://isogr.github.io/register-system-transition/, but JSON loading is not working as the expected URL base path is different.  The snapshot expects everything to be hosted at the top level path, and not under `/register-system-transition`.

**Comment by ribose-jeffreylau** [comment]
Modified scripts to make all base paths relative.  Now [the snapshot works fully](https://isogr.github.io/register-system-transition/) without relying on any specific base path configurations.

What remains is #22.

**Comment by ribose-jeffreylau** [comment]
I think this can be closed since https://isogr.github.io/register-system-transition/ is fully operational.  #22 is a separate issue.
