### ISSUE TITLE
sql2yaml: Superseding items do not get migrated

### ISSUE THREAD

**Issue by strogonoff** [isogr/register-system-transition#44]
If you look at “Successors” tab for transformation [484](https://geodetic-staging.isotc211.org/item/d2f8e859-4f30-463a-a189-fff86a2ba6f9) is superseded with transformation [739](https://geodetic-staging.isotc211.org/item/d2f8e859-4f30-463a-a189-fff86a2ba6f9).

This should be captured in YAML, but apparently isn’t.

It also is not captured in respective [proposal info](https://github.com/isogr/registry/blob/52890c1a721159be2fc5d87f0a06bc89f9731cc2/gr-registry/proposals/4ffc6a7d-3183-4087-96cd-3436b6a02f74/main.yaml#L9-L10): `supersedingItemIDs` should not be empty, if the old system knows which item superseded this one.

**Comment by strogonoff** [comment]
The cause may be because this item was *also* invalidated, and so the status is “invalid”. However, because it was also superseded, we want it to have “superseded” status, and the appropriate info about superseding items.

**Comment by strogonoff** [comment]
This may require an adjustment of data schema as well, to support independent supersession and invalidation.

**Comment by stefanomunarini** [comment]
Possibly fixed with https://github.com/isogr/register-system-transition/commit/8b5aef10ba1fc12c9626e6c435165bf1caa501f1 . Awaiting confirmation for data correctness

**Comment by strogonoff** [comment]
I.e. main file outside of proposal/items

**Comment by strogonoff** [comment]
To see how it’s supposed to look like, just supersede any item and approve the proposal, then you will see the correct YAML.

**Comment by stefanomunarini** [comment]
> To see how it’s supposed to look like, just supersede any item and approve the proposal, then you will see the correct YAML.

I am looking into doing this, however the button to start a new proposal cannot be clicked. My user is registered in the register metadata with role "owner". Am I missing another step here @strogonoff ?

**Comment by stefanomunarini** [comment]
And also, does this regard only Transformations dump, or shall this be for every single item class?

**Comment by stefanomunarini** [comment]
Superseding items have been added to all item class dump functions. However, it appears that only Transformation items have superseding items linked.
