### ISSUE TITLE
Update DNS for geodetic.isotc211.org to point to GitHub Pages of https://github.com/isogr/register-system-transition

### ISSUE THREAD

**Issue by ribose-jeffreylau** [isogr/register-system-transition#51]
As per #46, geodetic.isotc211.org needs to point to the GitHub Pages of this repository.

Currently, the domain for this repo's GitHub Pages is geodetic-static.isotc211.org, but needs to be changed to geodetic.isotc211.org .  (-> [go to settings](https://github.com/isogr/register-system-transition/settings/pages))

**Comment by ronaldtse** [comment]
@kwkwan can you please help facilitate? Thanks.

**Comment by kwkwan** [comment]
Related DNS record has been created.
